FROM bitnami/spark:3.5
USER root
RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN ln -sf /opt/bitnami/python/bin/python3 /usr/bin/python3
USER 1001
